### ISSUE TITLE
Git.io no longer accepts new URLs 

### ISSUE THREAD

**Issue by electriquo** [mahdyar/git.io-extension#10]
it was a nice ride...

> You can no longer create new URLs on git.io. Existing URLs will continue to be accessible, but we encourage using one of the many URL shortening services that are available, instead of git.io, as we will be deprecating the tool in the future.

[source](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/)

![image](https://user-images.githubusercontent.com/28758375/149279131-2762d882-19d9-487e-8e29-76712de7da9e.png)

**Comment by mahdyar** [comment]
Thank you @foolioo for letting me know about this. 
I'm going to archive this repository and close this issue. :)
