### ISSUE TITLE
support for keyboard shortcut

### ISSUE THREAD

**Issue by electriquo** [mahdyar/git.io-extension#6]
[could you please make this happened so we could save the hassle of clicking the mouse.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)
by default, it should generate a short link and if anyone want a custom url, then it must be done in the same way as now.

**Comment by mahdyar** [comment]
@foolioo It's actually a good idea, but how should I show the shortened link to the user? 🤔 any ideas about that?

**Comment by electriquo** [comment]
@mahdyar: copy to clipboard, such as [copy-shorturl](https://addons.mozilla.org/en-US/firefox/addon/copy-shorturl/)

**Comment by mahdyar** [comment]
> @mahdyar: copy to clipboard, such as [copy-shorturl](https://addons.mozilla.org/en-US/firefox/addon/copy-shorturl/)

Sounds good to me! It'll be implemented in a day or two. :)

**Comment by mahdyar** [comment]
@foolioo 
The shortcut is implemented. (`Ctrl/Command + Shift + L`). :)
Though it'll take some time to get approved on firefox addons and chrome web store...

**update:**
It's available on both chrome web store and firefox addons.

**Comment by electriquo** [comment]
@mahdyar: works like a charm! (https://git.io/JBhUv)
